FROM golang:1.25.1-alpine AS builder

RUN apk add --no-cache make git ca-certificates

WORKDIR /build

COPY . .

# Build arguments for version info
ARG VERSION=dev
ARG GIT_COMMIT=dev

# All code is pre-generated by the workflow, just build the binary
RUN VERSION=${VERSION} GIT_COMMIT=${GIT_COMMIT} make build-binary

FROM alpine:latest

RUN apk --no-cache add ca-certificates && \
    addgroup -g 1000 appuser && \
    adduser -D -u 1000 -G appuser appuser

WORKDIR /app

COPY --from=builder /build/bin/server .

RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8080

ENTRYPOINT ["/app/server"]

