services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: xatu-cbt-api-clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: testdb
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
