name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/go-setup
      - name: Install tools
        run: make install-tools
      - name: Create config.yaml for proto generation
        run: |
          cat > config.yaml << EOF
          clickhouse:
            dsn: "${{ secrets.CLICKHOUSE_DSN }}"
            database: "${{ secrets.CLICKHOUSE_DATABASE }}"
            discovery:
              prefixes:
                - fct

          proto:
            output_dir: "./pkg/proto/clickhouse"
            package: "cbt.v1"
            go_package: "github.com/ethpandaops/xatu-cbt-api/pkg/proto/clickhouse"
            include_comments: true

          api:
            base_path: "/api/v1"
            expose_prefixes:
              - fct
          EOF
      - name: Generate proto files
        run: make proto
      - name: Generate code
        run: make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
          args: --timeout=10m
